Repository everymeals/EveryMeal_Server, pull requests merged in 2023-09, with the labels that each got.

#14 [Chore/cd pipeline] 자동 배포 환경 구축
  .github/workflows/cd_prod.yml
  Dockerfile
Labels: Setting

#15 Deploy to DEV
  .github/workflows/cd_prod.yml
  .github/workflows/ci_dev.yml
  .github/workflows/sonar.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/everymeal/server/ServerApplication.java
  src/main/java/everymeal/server/global/config/MongoMappingConfig.java
  src/main/java/everymeal/server/global/config/SwaggerConfig.java
  src/main/java/everymeal/server/global/dto/response/ApplicationErrorResponse.java
  src/main/java/everymeal/server/global/dto/response/ApplicationResponse.java
  src/main/java/everymeal/server/global/exception/ApplicationException.java
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/global/exception/GlobalExceptionHandler.java
  src/main/java/everymeal/server/global/util/KakaoWebClientUtil.java
  src/main/java/everymeal/server/global/util/openapi/dto/response/Documents.java
  src/main/java/everymeal/server/global/util/openapi/dto/response/KakaoDto.java
  src/main/java/everymeal/server/global/util/openapi/dto/response/Meta.java
  src/main/java/everymeal/server/infra/HealthCheckController.java
  src/main/java/everymeal/server/meal/controller/MealController.java
  src/main/java/everymeal/server/meal/entity/Area.java
  src/main/java/everymeal/server/meal/entity/Meal.java
  src/main/java/everymeal/server/meal/entity/MealInfo.java
  src/main/java/everymeal/server/meal/entity/University.java
  src/main/java/everymeal/server/meal/repository/AreaRepository.java
  src/main/java/everymeal/server/meal/repository/MealRepository.java
  src/main/java/everymeal/server/meal/service/MealService.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/main/java/everymeal/server/store/controller/StoreController.java
  src/main/java/everymeal/server/store/entity/Store.java
  src/main/java/everymeal/server/store/repository/StoreRepository.java
  src/main/java/everymeal/server/store/service/StoreService.java
  src/main/java/everymeal/server/store/service/StoreServiceImpl.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/entity/Review.java
  src/main/java/everymeal/server/user/entity/Scrap.java
  src/main/java/everymeal/server/user/entity/User.java
  src/main/java/everymeal/server/user/repository/UserRepository.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/everymeal/server/ServerApplicationTests.java
  src/test/java/everymeal/server/global/ControllerTestSupport.java
  src/test/java/everymeal/server/global/IntegrationTestSupport.java
  src/test/java/everymeal/server/infra/HealthCheckControllerTest.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
  src/test/java/everymeal/server/store/controller/StoreControllerTest.java
  src/test/java/everymeal/server/store/service/StoreServiceImplTest.java
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
Labels: Deploy

#16 [chore/cd-pipeline] 도커 실행 시, 환경변수 주입 제거
  .github/workflows/cd_prod.yml
Labels: Setting

#17 Deploy for DEV
  .github/workflows/cd_prod.yml
Labels: Deploy

#18 [chore] 도커 태그 버전 관리 방식 변경
  .github/workflows/cd_prod.yml
  .github/workflows/ci_dev.yml
Labels: Setting

#19 Deploy for DEV
  .github/workflows/cd_prod.yml
  .github/workflows/ci_dev.yml
Labels: Deploy

#20 [chore] cd 태그 버전 제거
  .github/workflows/cd_prod.yml
Labels: Setting

#22 [Chore/cd-pipeline] CD 스크립트 주석 변경
  .github/workflows/cd_prod.yml
Labels: Setting

#24 [chore] cd 시크릿 변수명 수정
  .github/workflows/cd_prod.yml
Labels: Setting

#25 Deploy for DEV
  .github/workflows/cd_prod.yml
Labels: Deploy

#26 [chore] test를 위한 주석 변경
  .github/workflows/cd_prod.yml
Labels: Setting

#27 Deploy for DEV
  .github/workflows/cd_prod.yml
Labels: Deploy

#29 개발 환경별 yml 수정 (#13)
  .gitignore
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Setting

#30 Action 타겟 브랜치 develop로 변경 (#13)
  .github/workflows/cd_prod.yml
Labels: Setting

#32 [Feature/meal create] 학생식당, 주간식단 등록 및 당일 식단 조회 API 개발
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/meal/controller/MealController.java
  src/main/java/everymeal/server/meal/controller/dto/request/MealRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/request/RestaurantRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/request/WeekMealRegisterReq.java
  src/main/java/everymeal/server/meal/entity/Area.java
  src/main/java/everymeal/server/meal/entity/Meal.java
  src/main/java/everymeal/server/meal/entity/MealInfo.java
  src/main/java/everymeal/server/meal/entity/MealStatus.java
  src/main/java/everymeal/server/meal/entity/MealType.java
  src/main/java/everymeal/server/meal/entity/Restaurant.java
  src/main/java/everymeal/server/meal/repository/AreaRepository.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryCustom.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryImpl.java
  src/main/java/everymeal/server/meal/repository/RestaurantRepository.java
  src/main/java/everymeal/server/meal/service/MealService.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/main/java/everymeal/server/store/entity/Store.java
  src/main/java/everymeal/server/store/service/StoreServiceImpl.java
  src/main/resources/application.yml
  src/test/java/everymeal/server/global/ControllerTestSupport.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
Labels: Feature

#35 버전 업, 대학 도메인 추가 조회 API 개발
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd_prod.yml
  .github/workflows/ci_dev.yml
  build.gradle
  src/main/java/everymeal/server/global/config/MongoMappingConfig.java
  src/main/java/everymeal/server/global/config/QueryDslConfig.java
  src/main/java/everymeal/server/global/entity/BaseEntity.java
  src/main/java/everymeal/server/global/exception/ApplicationException.java
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/global/util/JwtUtil.java
  src/main/java/everymeal/server/meal/controller/MealController.java
  src/main/java/everymeal/server/meal/controller/dto/request/RestaurantRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/request/WeekMealRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/response/DayMealListGetRes.java
  src/main/java/everymeal/server/meal/controller/dto/response/RestaurantListGetRes.java
  src/main/java/everymeal/server/meal/controller/dto/response/WeekMealListGetRes.java
  src/main/java/everymeal/server/meal/entity/Meal.java
  src/main/java/everymeal/server/meal/entity/MealStatus.java
  src/main/java/everymeal/server/meal/entity/Restaurant.java
  src/main/java/everymeal/server/meal/entity/University.java
  src/main/java/everymeal/server/meal/entity/UniversityEnum.java
  src/main/java/everymeal/server/meal/repository/MealRepository.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryCustom.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryImpl.java
  src/main/java/everymeal/server/meal/repository/RestaurantRepository.java
  src/main/java/everymeal/server/meal/service/MealService.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/main/java/everymeal/server/store/entity/Store.java
  src/main/java/everymeal/server/store/repository/StoreRepository.java
  src/main/java/everymeal/server/university/controller/UniversityController.java
  src/main/java/everymeal/server/university/controller/dto/response/UniversityListGetRes.java
  src/main/java/everymeal/server/university/entity/University.java
  src/main/java/everymeal/server/university/repository/UniversityRepository.java
  src/main/java/everymeal/server/university/service/UniversityService.java
  src/main/java/everymeal/server/university/service/UniversityServiceImpl.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/controller/dto/response/UserLoginRes.java
  src/main/java/everymeal/server/user/entity/Review.java
  src/main/java/everymeal/server/user/entity/Scrap.java
  src/main/java/everymeal/server/user/entity/User.java
  src/main/java/everymeal/server/user/entity/Users.java
  src/main/java/everymeal/server/user/repository/UserRepository.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/db/data.sql
  src/main/resources/db/shema.sql
  src/test/java/everymeal/server/global/ControllerTestSupport.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
  src/test/java/everymeal/server/university/controller/UniversityControllerTest.java
  src/test/java/everymeal/server/university/service/UniversityServiceImplTest.java
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
  src/test/resources/application.yml
Labels: Feature, Setting, Test

#38 [Feature/user-profile-create] 유저 인증 여부 API 구현 완료
  .github/workflows/cd_prod.yml
  .github/workflows/ci_dev.yml
  .gitignore
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/global/util/JwtUtil.java
  src/main/java/everymeal/server/global/util/authresolver/Auth.java
  src/main/java/everymeal/server/global/util/authresolver/AuthUser.java
  src/main/java/everymeal/server/global/util/authresolver/UserJwtResolver.java
  src/main/java/everymeal/server/global/util/authresolver/entity/AuthenticatedUser.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/entity/Review.java
  src/main/java/everymeal/server/user/entity/Scrap.java
  src/main/java/everymeal/server/user/entity/User.java
  src/main/java/everymeal/server/user/repository/UserRepository.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/main/resources/application-test.yml
  src/test/java/everymeal/server/global/ControllerTestSupport.java
  src/test/java/everymeal/server/infra/HealthCheckControllerTest.java
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
Labels: Feature, Test

#39 Docker jdk 17 변경
  Dockerfile
Labels: Setting

#41 feature : 이메일 전송/인증 API 구현 완료
  build.gradle
  src/main/java/everymeal/server/global/config/WebMvcConfig.java
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/global/util/JwtUtil.java
  src/main/java/everymeal/server/global/util/MailUtil.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/controller/dto/request/UserEmailAuthReq.java
  src/main/java/everymeal/server/user/controller/dto/request/UserEmailAuthVerifyReq.java
  src/main/java/everymeal/server/user/controller/dto/request/UserProfileCreateReq.java
  src/main/java/everymeal/server/user/controller/dto/response/UserEmailAuthRes.java
  src/main/java/everymeal/server/user/entity/User.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
Labels: Feature, Test
