Repository everymeals/EveryMeal_Server, pull requests merged in 2023-10, with the labels that each got.

#42 refactor : 유저 로그인, 회원가입 DTO 생성
  src/main/java/everymeal/server/global/util/MailUtil.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/controller/dto/request/UserSingReq.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
Labels: Refactor

#43 [Test/meal-service] 식사 관련 API 테스트 코드 작성 ( 실패 케이스 ) 및 리펙토링
  src/main/java/everymeal/server/meal/controller/dto/request/MealRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/request/RestaurantRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/request/WeekMealRegisterReq.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryImpl.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
Labels: Refactor, Test

#46 [Fix/meal create] 식사 도메인 내 API 수정
  src/main/java/everymeal/server/global/aop/log/LogAspect.java
  src/main/java/everymeal/server/global/aop/log/LogTrace.java
  src/main/java/everymeal/server/global/aop/log/Pointcuts.java
  src/main/java/everymeal/server/global/aop/log/TraceInfo.java
  src/main/java/everymeal/server/global/config/QueryDslConfig.java
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/meal/controller/MealController.java
  src/main/java/everymeal/server/meal/controller/dto/request/MealRegisterReq.java
  src/main/java/everymeal/server/meal/controller/dto/response/DayMealListGetRes.java
  src/main/java/everymeal/server/meal/controller/dto/response/WeekMealListGetRes.java
  src/main/java/everymeal/server/meal/entity/Meal.java
  src/main/java/everymeal/server/meal/entity/MealCategory.java
  src/main/java/everymeal/server/meal/entity/MealStatus.java
  src/main/java/everymeal/server/meal/entity/MealType.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryCustom.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryImpl.java
  src/main/java/everymeal/server/meal/service/MealService.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
Labels: Feature

#54 fix: #44 학식 파트 Response 응답 record로 변경
  src/main/java/everymeal/server/meal/controller/dto/response/DayMealListGetRes.java
  src/main/java/everymeal/server/meal/controller/dto/response/RestaurantListGetRes.java
  src/main/java/everymeal/server/meal/controller/dto/response/WeekMealListGetRes.java
  src/main/java/everymeal/server/meal/repository/MealRepositoryImpl.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
Labels: Refactor
