Repository everymeals/EveryMeal_Server, pull requests merged in 2024-02, with the labels that each got.

#86 [fix/store-post-review] 식당 상세 조회 및 주변식당 리뷰 api request 수정
  src/main/java/everymeal/server/global/exception/ExceptionList.java
  src/main/java/everymeal/server/global/util/JwtUtil.java
  src/main/java/everymeal/server/review/controller/ReviewController.java
  src/main/java/everymeal/server/review/dto/request/ReviewStoreCreateReq.java
  src/main/java/everymeal/server/review/repository/ImageRepository.java
  src/main/java/everymeal/server/review/service/ReviewService.java
  src/main/java/everymeal/server/review/service/ReviewServiceImpl.java
  src/main/java/everymeal/server/store/controller/StoreController.java
  src/main/java/everymeal/server/store/controller/dto/response/StoreGetReviewRes.java
  src/main/java/everymeal/server/store/controller/dto/response/StoresGetReviews.java
  src/main/java/everymeal/server/store/service/StoreService.java
  src/main/java/everymeal/server/store/service/StoreServiceImpl.java
  src/main/java/everymeal/server/user/controller/UserController.java
  src/main/java/everymeal/server/user/service/UserService.java
  src/main/java/everymeal/server/user/service/UserServiceImpl.java
  src/main/resources/mybatis/mappers/StoreMapper.xml
  src/test/java/everymeal/server/review/service/ReviewServiceImplTest.java
  src/test/java/everymeal/server/store/service/StoreServiceImplTest.java
  src/test/java/everymeal/server/user/controller/UserControllerTest.java
  src/test/java/everymeal/server/user/service/UserServiceImplTest.java
Labels: Fix

#93 feat(#92): 이미지 삭제/조회 api 개발 및 리뷰 수정 로직 변경
  build.gradle
  src/main/java/everymeal/server/admin/controller/AdminController.java
  src/main/java/everymeal/server/admin/dto/AdminUserDto.java
  src/main/java/everymeal/server/admin/entity/UserDefaultProfileImage.java
  src/main/java/everymeal/server/admin/repository/UserDefaultProfileImageRepository.java
  src/main/java/everymeal/server/admin/service/AdminUserService.java
  src/main/java/everymeal/server/global/util/aws/S3Util.java
  src/main/java/everymeal/server/global/util/aws/controller/S3Controller.java
  src/main/java/everymeal/server/review/dto/request/ReviewCreateReq.java
  src/main/java/everymeal/server/review/entity/Image.java
  src/main/java/everymeal/server/review/entity/Review.java
  src/main/java/everymeal/server/review/repository/ReviewRepositoryImpl.java
  src/main/java/everymeal/server/review/service/ImageCommServiceImpl.java
  src/main/java/everymeal/server/review/service/ReviewServiceImpl.java
Labels: Feature, Fix

#98 [Fix/meal service] universityIdx 통일화 작업
  src/main/java/everymeal/server/meal/controller/MealController.java
  src/main/java/everymeal/server/meal/controller/dto/request/RestaurantRegisterReq.java
  src/main/java/everymeal/server/meal/entity/Restaurant.java
  src/main/java/everymeal/server/meal/repository/MealMapper.java
  src/main/java/everymeal/server/meal/service/MealCommServiceImpl.java
  src/main/java/everymeal/server/meal/service/MealService.java
  src/main/java/everymeal/server/meal/service/MealServiceImpl.java
  src/main/java/everymeal/server/meal/service/RestaurantService.java
  src/main/java/everymeal/server/meal/service/RestaurantServiceImpl.java
  src/main/java/everymeal/server/university/repository/UniversityRepository.java
  src/main/java/everymeal/server/university/service/UniversityService.java
  src/main/java/everymeal/server/university/service/UniversityServiceImpl.java
  src/main/resources/mybatis/mappers/MealMapper.xml
  src/test/java/everymeal/server/meal/MealData.java
  src/test/java/everymeal/server/meal/controller/MealControllerTest.java
  src/test/java/everymeal/server/meal/service/MealServiceImplTest.java
Labels: Refactor, Fix
